language: node_js
node_js:
- '8'
cache: yarn
script: yarn test
deploy:
  provider: npm
  email: igor@kamyshev.me
  api_key:
    secure: jnbUHtChcVb612LINt0ArcQ9TkU7d7Ztdk+yp72+Hdi/ReqcxS4WUNsblEWLpPixi2R9/LHMCNvSBx+Ldb5WypWE5NT3a0TTRD7Y0PPjYXRSFHlrkGteNmml0XREURdQM9vf6ngvpD2AzCyPZ70Ts3M1RmLOOBRnTqrP8U3Rso400WIyvQOWa2EpynFSbHhXfPU9d3sG04qL/xnXnP4keBbGFnPsSwGA/MaMtAuSr5b7W61gUUa98ACxTYmkVlwTRerZwSRQ6OxRab/RQVulk5cdJ01tU5VZMz9LGSVmGrOhy2RuL+jirm9Ken2U4eJvT8IbGJFMVFmLc+txqoL4W9mw5rGaCsTvWWWbd2bAAYv4lg1zQqy1IiHz3l21f+geWShH4NlpzuUp89+jHdy5et51od6aysA0qZmlqKboWcfazo7zxWoe/vPDclINp+drkoAjRMdnGZfnA34WJNKHMy6xKgxw2rVl3sWI3bSw2QYhx0P6oV9jl6h2ukZOf2lAzhopQRKgqwAG22AH2L8C1b1CFYan1TJ88T9SUfmekj8ed25HTSLuY1JESqtxPoeSMHNpaj6TBWrLJ952pKcWCY7ZviDL+stmGsavbDVT+upisl8jtLtRLrwESWK4a7TZtqguCIsTSfNOH+DvNsS4ZMFvjMHRWxpzb9nrCzfjjoc=
  on:
    tags: true
    repo: breadhead/nest-throwable-bus
